# bashrc
export CFLAGS="-march=k8 -pipe -O2"
export CXXFLAGS="-march=k8 -pipe -O2"
export CHOST="x86_64-pc-linux-gnu"
export MAKEOPTS="-j1"

#ccache
if [ -x /usr/bin/ccache ]; then
    PATH="/usr/lib/ccache/bin/:${PATH}"
    CCACHE_DIR="/var/tmp/ccache"
    SANDBOX_WRITE="${SANDBOX_WRITE}:${CCACHE_DIR}"
fi
