# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{Athenry}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Greg Fitzgerald"]
  s.date = %q{2009-11-03}
  s.default_executable = %q{athenry}
  s.description = %q{Opinionated tool to build Gentoo stages.}
  s.email = %q{netzdamon@gmail.com}
  s.executables = ["athenry"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     ".gitmodules",
     "AUTHORS.markdown",
     "BUGS",
     "MIT-LICENSE",
     "README.markdown",
     "Rakefile",
     "TODO.markdown",
     "bin/athenry",
     "config.yml",
     "doc/about.markdown",
     "doc/notes/bash_organization.txt",
     "doc/quickstart.markdown",
     "lib/athenry.rb",
     "lib/athenry/commands.rb",
     "lib/athenry/commands/build.rb",
     "lib/athenry/commands/clean.rb",
     "lib/athenry/commands/resume.rb",
     "lib/athenry/commands/setup.rb",
     "lib/athenry/config.rb",
     "lib/athenry/helper.rb",
     "lib/athenry/resumetree.rb",
     "lib/athenry/run.rb",
     "lib/athenry/shell.rb",
     "lib/athenry/shell/aliases.rb",
     "lib/athenry/shell/shell.rb",
     "lib/athenry/state.rb",
     "lib/athenry/templates/bashconfig.erb",
     "lib/athenry/templates/help.txt",
     "scripts/compile.sh"
  ]
  s.homepage = %q{http://github.com/gregf/athenry}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Opinionated tool to build Gentoo stages.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<visionmedia-commander>, [">= 3.2"])
      s.add_runtime_dependency(%q<configatron>, [">= 2.5"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<visionmedia-commander>, [">= 3.2"])
      s.add_dependency(%q<configatron>, [">= 2.5"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<visionmedia-commander>, [">= 3.2"])
    s.add_dependency(%q<configatron>, [">= 2.5"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

